spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/version_2}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:31102005}

    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 0
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      initialization-fail-timeout: 60000
      auto-commit: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      username: ${SPRING_DATA_REDIS_USERNAME:}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

      ssl:
        enabled: false

      repositories:
        enabled: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:root}
    password: ${SPRING_RABBITMQ_PASSWORD:31102005}

  jpa:
    hibernate:
      ddl-auto: validate # none, validate, update, create, create-drop, update
    database: postgresql
    show-sql: true
    open-in-view: true
    repositories:
      enabled: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        connection:
          provider_disables_autocommit: true
#        temp:
#          use_jdbc_metadata_defaults: false
#        boot:
#          allow_jdbc_metadata_access: false

  sql:
    init:
      mode: never

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: ERROR
    org.springframework.security: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.postgresql: WARN
    root: INFO

    org.springframework.web: DEBUG

jwt:
  base64-secret: ${JWT_BASE64_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

password:
  time_password_change_days: ${TIME_PASSWORD_CHANGE_DAYS}

cache:
  ttl:
    one-day-seconds: 86400
    one-week-seconds: 604800
    one-month-seconds: 2592000

bytescale:
  account-id: ${BYTESCALE_ACCOUNT_ID}
  api-key: ${BYTESCALE_API_KEY}

server:
  port: ${PORT:8080}
  address: 0.0.0.0

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
